[project]
name = "ai-dubber-ultimate-v1-2-9-portable"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.8.5",
    "deep-translator>=1.11.4",
    "edge-tts>=6.1.9",
    "huggingface-hub>=0.20.0",
    "numpy>=1.24.0",
    "opencv-python-headless>=4.8.0",
    "pillow>=10.0.0",
    "psutil>=5.9.5",
    "pydub>=0.25.1",
    "pyqt5>=5.15.9",
    "pywin32>=306 ; sys_platform == 'win32'",
    "qtawesome>=1.3.0",
    "requests>=2.31.0",
    "soundfile>=0.12.1",
    "tqdm>=4.66.0",
    "yt-dlp>=2024.3.10",
]
